title: Psi-Continuum Project
description: Independent Research in Cosmology
remote_theme: pmarsceill/just-the-docs   # очень красиво для документации

markdown: kramdown

# Just-the-Docs настройки (если выбрал эту тему)
color_scheme: light   # или dark
search_enabled: true
heading_anchors: true
