theme: jekyll-theme-cayman

title: Psi-Continuum v2 Documentation
description: Minimal phenomenological extension of ΛCDM with one parameter ε₀

markdown: kramdown
kramdown:
  input: GFM   # поддержка GitHub Markdown, таблиц, списков, подчёркивания
  hard_wrap: false

# Позволяет использовать относительные пути в Markdown без ошибок
relative_links:
  enabled: true
  collections: true

highlighter: rouge

include:
  - assets/custom.css

# Чтобы Jekyll не ругался на директорий docs/v2
exclude:
  - README.md

baseurl: "/docs/v2"
